### ISSUE TITLE
Cosmic Exploration - "Display on Map" doesn't show a mission area

### ISSUE THREAD

**Issue by TheMusicMeister** [MidoriKami/Mappy#209]
Clicking on "Display on Map" to preview the quest area for a Cosmic Exploration mission doesn't show anything.

Expected Behavior:
A mission zone should display showing the area for the mission.

Actual Behavior:
No mission zone radius is displayed.

First screenshot is from the default game map when the "Display on Map" button is clicked:
![Image](https://github.com/user-attachments/assets/dba6c724-2c4d-4221-b980-7e8153dd3102)

Second screenshot is from Mappy when clicking the same mission:
![Image](https://github.com/user-attachments/assets/cdda6186-d15a-48a2-8f0c-de831759d2ec)

**Comment by MidoriKami** [comment]
This seems to be a new system that was recently added to FFXIV.

It would need to be reverse engineered and implemented to work. I am not actively paying FFXIV at this time and am not willing to put in the hours it would take to implement this. 

A PR to implement this would be welcomed.

**Comment by MidoriKami** [comment]
Can you include more pictures or a video of what triggers this behavior?

**Comment by TheMusicMeister** [comment]
It is indeed a new system.  The implementation *seems* similar to how the levequest location preview system works, but I'm not familiar enough with the internal workings of XIV to really know.  If you're no longer active then I don't think this is something worth the time to implement, but I thought I'd report it here anyway just for tracking purposes.

If I have time, I can try to dig into the Dalamud <=> Game interface stuff and see if I can find the connection, but for the time being I don't think Dalamud has updated to include many of the new things either, so I wouldn't worry about it much.

**Comment by harbingerftw** [comment]
I have looked into it and discovered they do not set the IconId for these. After figuring out how things worked and messing around, just setting the IconId when temporary map markers are drawn fixes the issue. 
@MidoriKami I have no real idea how any of this works so please let me know what you think of this, I am going to keep looking if there is another way to make it work.
```csharp
 if (marker.MapMarker.IconId == 0)
    marker.MapMarker.IconId = 60492;
```

**Comment by MidoriKami** [comment]
> I have looked into it and discovered they do not set the IconId for these. After figuring out how things worked and messing around, just setting the IconId when temporary map markers are drawn fixes the issue. [@MidoriKami](https://github.com/MidoriKami) I have no real idea how any of this works so please let me know what you think of this, I am going to keep looking if there is another way to make it work. I will make a PR depending on what I find out and your feedback.
> 
>  if (marker.MapMarker.IconId == 0)
>     marker.MapMarker.IconId = 60492;

I'd need to see a PR to see the context of this suggestion to be able to comment.

**Comment by MidoriKami** [comment]
Potentially fixed in a638ea26db56a2b0b11d1edf9f86343c508c4500

**Comment by harbingerftw** [comment]
It does not fix it, this still throws: https://github.com/MidoriKami/Mappy/blob/ceb22f61baa334d40e02d1d1711cb9777af057f3/Mappy/Controllers/IntegrationsController.cs#L208-L211 
additionally, the circle is still not displayed.
